# Generated by Django 6.0.1 on 2026-05-06 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_experience_years_doctor_license_number_and_more'),
        ('medicalrecords', '0002_medicalrecord_attachment_alter_medicalrecord_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
