# Generated by Django 6.0.1 on 2026-05-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Nouvelle conversation', max_length=200),
        ),
    ]
