# Generated by Django 6.0.1 on 2026-03-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_created_at_appointment_reason_and_more'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_details', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, verbose_name='Ordonnance'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True, verbose_name='Symptômes'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnostic'),
        ),
    ]
