# Generated by Django 6.0.1 on 2026-05-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_appointment_consultation_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='video_room_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de salle vidéo'),
        ),
    ]
