# Generated by Django 6.0.1 on 2026-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_created_at_appointment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
